export const icons ={
    searchicon: require('./Vector.png'),
    locationicon:require('./Frame.png'),
    ArrowRight: require('./RightArrow.png'),
    GoArrow: require('./GoArrow.png'),
    Support:require('./OBJECTS.png'),
    insta: require('./insta.png'),
    facebook:require('./facebook.png'),
    linkedin:require('./linkedin.png'),
    twitter:require('./tiwter.png'),
    profile:require('./profile.png'),
    Event:require('./Event.png'),
    Threedot:require('./Dot.png'),
    ticket:require('./Ticket.png'),
    Line:require('./Line.png'),
    Qr:require('./qr-code.png'),
    down:require('./DownIcons.png'),
    Calender:require('./Calender.png'),
    UpArrow:require('./UpArrow.png'),
    CheckBox:require('./CheckBox.png'),
    BackArrow:require('./Arrowback.png'),
    Iicon:require('./Iicon.png'),
    confirm:require('./confirm.png'),
    calender2:require('./calender2.png'),
    location2:require('./location2.png'),
}